name = "status"
account_id = "00db1aa44db3e48950f14da66e575518"
workers_dev = true
main = "./.svelte-kit/cloudflare/"
compatibility_date = "2023-04-19"
compatibility_flags = [ "nodejs_compat" ]

[triggers]
crons = ["*/30 * * * *"]

[site]
bucket = ".svelte-kit/output/"
